apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY }}
  BASIC_AUTH_USERNAME: {{ .Values.secrets.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_PASSWORD: {{ .Values.secrets.BASIC_AUTH_PASSWORD }}
