replicaCount: 1

image:
  repository: # TODO
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  host: your-domain.com
  clusterIssuer: letsencrypt-prod
  email: your-email@example.com

env:
  GCP_BUCKET_NAME:
  GCP_DEFAULT_KMS_KEY:
  GCP_KEY_RING_ID:
  GCP_PROJECT_ID:
  GCP_REGION:
  JWT_ALGORITHM:
  JWT_EXPIRE_MINUTES:
  JWT_SECRET_KEY:

resources:
  limits:
    memory: "256Mi"
  requests:
    memory: "256Mi"
