name: CI/CD Pipeline with GKE & Static Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
  CLUSTER_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE: gcs-fastapi-app
  RELEASE_NAME: gcs-fastapi-app
  CHART_PATH: ./helm/gcs-fastapi-app
  DOMAIN: ${{ secrets.APP_DOMAIN }}
  EMAIL: ${{ secrets.APP_EMAIL }}
  BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  FRONTEND_BUCKET: ${{ secrets.GCP_PROJECT_ID }}-frontend

jobs:
#   test:
#     name: Run Unit Tests
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.12
#
#       - name: Install dependencies
#         run: |
#           pip install --upgrade pip
#           pip install -r requirements.txt
#           pip install pytest
#
#       - name: Run tests
#         run: pytest tests/

  deploy:
    name: Deploy to GKE and Static Frontend
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/gcs-fastapi-repo/${{ env.IMAGE }}:$GITHUB_SHA .
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/gcs-fastapi-repo/${{ env.IMAGE }}:$GITHUB_SHA

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_ID }}

      - name: Deploy backend with Helm
        run: |
          helm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.CHART_PATH }}             --set image.repository=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/gcs-fastapi-repo/${{ env.IMAGE }}             --set image.tag=$GITHUB_SHA             --set ingress.host=${{ env.DOMAIN }}             --set ingress.email=${{ env.EMAIL }}             --set env.JWT_SECRET_KEY=${{ env.JWT_SECRET_KEY }}             --set env.GCP_BUCKET_NAME=${{ env.BUCKET_NAME }}

      - name: Upload static frontend to GCS
        run: |
          gsutil -m cp -r frontend/* gs://${{ env.FRONTEND_BUCKET }}
          gsutil web set -m index.html -e index.html gs://${{ env.FRONTEND_BUCKET }}
